stages:
  - deploy
  - test

build:
  stage: deploy
  image: golang
  before_script:
    - export GOPATH=`pwd`/player
  script:
    - go get ./... || true
    - go get ./player/src/github.com/rakyll/statik
    - cd player/src
    - ../bin/statik -f -src=../../manager/go_web
    - CGO_ENABLED=0 go install github.com/majeinfo/chaingun/player
    - cd ..
    - bin/player -h || [ $? -eq 2 ]
  artifacts:
    paths:
      - player/bin/
    
test1:
  stage: test
  image: docker
  services:
    - docker:dind
  script:
    - cd tests
    - /bin/sh run_web_server.sh
    - netstat -tlnp
    - docker container ps -a
    - /bin/sh test_standalone_player.sh
    - docker container rm -f $(docker container ps -qa)
