stages:
  - deploy
  - test

build:
  stage: deploy
  image: golang:1.16
  before_script:
    - export GOPATH=`pwd`/player
  script:
    - cd player/src
    - CGO_ENABLED=0 go install -ldflags="-s -w" ./player
    - cd ..
    - bin/player -h || [ $? -eq 2 ]
  artifacts:
    paths:
      - player/bin/
    
test1:
  stage: test
  image: golang:1.16
  before_script:
    - export GOPATH=`pwd`/player
  script:
    - go get github.com/majeinfo/chaingun
    - go test github.com/majeinfo/chaingun/config
    - go test github.com/majeinfo/chaingun/utils

test2:
  stage: test
  image: docker
  services:
    - docker:dind
  script:
    - cd tests
    - /bin/sh run_web_server.sh
    - docker container ps -a
    - /bin/sh test_standalone_player.sh
    - docker container rm -f $(docker container ps -qa)
