---
iterations: 500
users: 2000
rampup: 60
feeder:
  type: csv #csv, json
  filename: samples/fleetdata.csv
actions:
  - sleep:
      duration: 1
  - http:
      title: Submit data
      method: POST
      url: http://localhost:10000
      accept: json
      body: '{"vehicleid":${UID},"lat":${lat},"lon":${lon}}'
  - sleep:
      duration: 1
  - tcp:
      title: TCP packet
      address: 127.0.0.1:8181
      payload: ${UID}|${dp1}|${dp2}|${dp3}|${dp4}|${dp5}
