---
iterations: 2
users: 2
rampup: 4
feeder:
  type: csv
  filename: data1.csv
  separator: ","
default:
  server: www.delamarche.com
  protocol: https
actions:
  - http:
      title: Page 1
      method: GET
      url: /chaingun/page1.php
      store_cookie: __all__
  - http:
      title: Page 2
      method: GET
      url: /chaingun/page2.php
  - http:
      title: Page 3
      method: GET
      url: /chaingun/page3.php?nom=${nom}
  - http:
      title: Page 4
      method: POST
      url: /chaingun/page4.php
      body: nom=${nom}&age=${age}
      responses:
        - regex: "is: (.*)<br>"
          index: first
          variable: address
  - http:
      title: Page 5
      method: GET
      url: /chaingun/page5.php?address=${address}
  - http:
      title: Page 4bis
      method: POST
      url: /chaingun/page4.php
      body: nom=${nom}&age=${age}
      responses:
        - regex: "is: (.*), (.*)<br>"
          index: first
          variable: address
  - http:
      title: Page 5bis
      method: GET
      url: /chaingun/page5.php?address=${address}
