---
iterations: 1
users: 1
rampup: 1
timeout: 3
actions:
  - http:
      title: Page 1
      method: GET
      url: http://www.delamarche.com/chaingun/page1.php
      store_cookie: __all__
  - http:
      title: Page 2
      method: GET
      url: http://www.delamarche.com/chaingun/page2_timeout.php
      responses:
        - regex: Bonjour
  - http:
      title: Page SSL
      method: GET
      url: https://www.delamarche.com:443/
