---
iterations: 1
users: 1
rampup: 1
default:
  server: www.delamarche.com:80
  protocol: http
  method: GET
on_error: stop_test
actions:
  - http:
      title: Page 1
      url: /page1.php
      storeCookie: __all__
  - http:
      title: Page 2
      url: page2.php
  - http:
      title: Page SSL
      method: GET
      url: https://www.delamarche.com:443/
  - http:
      title: Page SSL2
      method: POST
      url: /
