---
iterations: 1
users: 1
rampup: 1
persistent_db_connections: true

default:
  server: mongodb://localhost:27017
  database: testing
  collection: numbers

variables:
  nom: fred

pre_actions:
  - mongodb:
      title: Réinit
      command: drop

actions:
  - mongodb:
      title: Insertion
      command: insertone
      document: '{"nom": "${nom}", "age": 30, "enfants" : [ {"prenom": "alice"}, {"prenom": "dede"} ]}'
  - mongodb:
      title: Recherche
      command: findone
      filter: '{"age": { "$eq": 30}}'
      responses:
        - jsonpath: $.nom+
          variable: nom2
          index: first
          default_value: alice
  - log:
      message: "le nom est ${nom2}"

