---
iterations: 1
users: 1
rampup: 1

feeder:
  type: csv
  filename: data1.csv
  separator: ","

actions:
  - http:
      title: Page upload
      method: POST
      url: http://www.delamarche.com/upload.php
      formdata:
        - name: nom
          value: ${nom} Dupont
        - name: adresse
          value: rue des Buissonnets
        - name: fileToUpload
          value: un_fichier.txt
          type: file
        - name: submit
          value: "1"
