---
iterations: 1
users: 1
rampup: 1
actions:
  - http:
      title: Page 1
      method: GET
      url: http://www.delamarche.com/chaingun/page1.php
      storeCookie: __all__
  - http:
      title: Page 2
      method: GET
      url: http://www.delamarche.com/chaingun/page2-json.php
      responses:
        - jsonpath: $.NOM+
          variable: nom
          index: first
          default_value: alice
        - jsonpath: $.AGE+
          variable: age
          index: first
          default_value: "99"
  - http:
      title: Page 3
      method: GET
      url: http://www.delamarche.com/chaingun/page3.php?nom=${nom}&age=${age}
