---
iterations: 1
users: 1
rampup: 1
on_error: stop_vu
actions:
  - http:
      title: Page 1
      method: GET
      url: http://www.delamarche.com/chaingun/page1.php
      store_cookie: __all__
  - http:
      title: Page 2
      method: GET
      url: http://www.delamarche.com/chaingun/page2.php
      responses:
        - regex: "Bnjour (.*)"
          index: first
          variable: nom
          dfault_value: alice
  - http:
      title: Page 3
      method: GET
      url: http://www.delamarche.com/chaingun/page3.php?nom=${nom}
