---
iterations: 5
users: 1000
rampup: 30
actions:
  - http:
      method: GET
      url: http://localhost:9183/courses
      accept: json
      response:
        jsonpath: $[*].id+
        variable: courseId
        index: first # first, random, last
  - sleep:
      duration: 3
  - http:
      method: GET
      url: http://localhost:9183/courses/${courseId}
      accept: json
      response:
        jsonpath: $.author+
        variable: author
        index: first # first, random, last
  - sleep:
        duration: 3
  - http:
      method: POST
      url: http://localhost:9183/courses
      body: '{"id":100,"name":"Fjällbacka","author":"${author}-${courseId}","created":"2015-10-23T21:33:38.254+02:00","baseLatitude":45.634353,"baseLongitude":11.3424324,"holes":[]}'
      accept: json
  - sleep:
      duration: 2